name: taxi_booking
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # TOAST
  fluttertoast: ^8.2.4

  # IMAGE
  cached_network_image: ^3.3.1

  # BASE
  intl: ^0.18.1
  # google_fonts: ^6.2.1
  html: ^0.15.4
  shared_preferences: ^2.3.2
  # flutter_widget_from_html: ^0.14.11

  # UI
  sliding_up_panel: ^2.0.0+1
  dotted_line: ^3.2.2
  lottie: ^3.1.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  bottom_picker: ^2.4.0
  country_code_picker: ^3.0.0
  flutter_native_contact_picker: ^0.0.6
  dotted_border: ^2.1.0
  flutter_countdown_timer: ^4.1.0
  timeline_tile: ^2.0.0
  flutter_vector_icons: ^2.0.0

  #OTP TEXTFIELD
  otp_text_field: ^1.1.3

  # MAP
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.0
  flutter_polyline_points: ^2.0.0
  google_maps_place_picker_mb: ^3.1.2

  # IMAGES
  image_picker: ^1.0.7
  file_picker: ^6.2.0

  # CONNECTIVITY
  package_info_plus: ^5.0.1

  # CONNECTIVITY
  http: ^1.2.1
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.5

  #FIREBASE
  firebase_crashlytics: ^4.1.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.3
  firebase_database: ^11.1.4
  paginate_firestore: ^1.0.3+1
  cloud_firestore: ^5.4.4
  firebase_core_platform_interface: ^5.3.0

  # STATE MANAGEMENT
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0

  flutter_native_splash: ^2.4.0

  # Payment gateway
  # razorpay_flutter: ^1.3.6
  # flutter_stripe: ^10.1.1
  # flutter_paystack: ^1.0.7
  # flutter_braintree: ^4.0.0
  # flutterwave_standard: ^1.0.8
  # flutter_paytabs_bridge: ^2.6.7
  #  mercado_pago_mobile_checkout: ^0.2.0-dev.3
  # my_fatoorah: ^3.3.0
  # paytm: ^3.0.1

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.1.2

  # MQTT
  mqtt_client: ^10.2.0

  # Social Login
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1

  # DOWNLOAD INVOICE PDF
  pdf: ^3.10.8
  path_provider: ^2.1.2
  open_file: ^3.3.2
  printing: ^5.12.0

  flutter_localizations:
    sdk: flutter
  intl_phone_field: ^3.2.0
  flutter_svg: ^2.0.10+1
  flutter_easyloading: ^3.0.5
  pinput: ^4.0.0
  video_player: ^2.8.6
  flutter_launcher_icons: ^0.13.1
  pdf_widget_wrapper: ^1.0.4
  equatable: ^2.0.5
  flutter_keyboard_visibility: ^6.0.0
  supabase_flutter: ^2.6.0
  vector_math: ^2.1.4
  dropdown_button2: ^2.3.9
  #stream_chat_flutter: ^7.2.2
  #responsive_builder: ^0.7.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  intl: ^0.18.0
  http: ^0.13.5
  cloud_firestore: ^5.4.4
  package_info_plus: ^4.1.0
  # web: 0.3.0
  geolocator: ^10.0.1

flutter_native_splash:
  image: images/splash.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/flag/
    - images/icons/
    - images/map_style.json
    - images/location.png
    - images/close_bar.png
    - images/profile_bar.png


  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/TajawalRegular.ttf
          weight: 400
